// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/capservice.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapRequest) Reset() {
	*x = CapRequest{}
	mi := &file_proto_capservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapRequest) ProtoMessage() {}

func (x *CapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_capservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapRequest.ProtoReflect.Descriptor instead.
func (*CapRequest) Descriptor() ([]byte, []int) {
	return file_proto_capservice_proto_rawDescGZIP(), []int{0}
}

func (x *CapRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type CapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapResponse) Reset() {
	*x = CapResponse{}
	mi := &file_proto_capservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapResponse) ProtoMessage() {}

func (x *CapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_capservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapResponse.ProtoReflect.Descriptor instead.
func (*CapResponse) Descriptor() ([]byte, []int) {
	return file_proto_capservice_proto_rawDescGZIP(), []int{1}
}

func (x *CapResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_proto_capservice_proto protoreflect.FileDescriptor

const file_proto_capservice_proto_rawDesc = "" +
	"\n" +
	"\x16proto/capservice.proto\x12\x12capitalize_service\"&\n" +
	"\n" +
	"CapRequest\x12\x18\n" +
	"\aPayload\x18\x01 \x01(\tR\aPayload\"'\n" +
	"\vCapResponse\x12\x18\n" +
	"\aPayload\x18\x01 \x01(\tR\aPayload2[\n" +
	"\n" +
	"CapService\x12M\n" +
	"\n" +
	"Capitalize\x12\x1e.capitalize_service.CapRequest\x1a\x1f.capitalize_service.CapResponseB\x06Z\x04.;pbb\x06proto3"

var (
	file_proto_capservice_proto_rawDescOnce sync.Once
	file_proto_capservice_proto_rawDescData []byte
)

func file_proto_capservice_proto_rawDescGZIP() []byte {
	file_proto_capservice_proto_rawDescOnce.Do(func() {
		file_proto_capservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_capservice_proto_rawDesc), len(file_proto_capservice_proto_rawDesc)))
	})
	return file_proto_capservice_proto_rawDescData
}

var file_proto_capservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_capservice_proto_goTypes = []any{
	(*CapRequest)(nil),  // 0: capitalize_service.CapRequest
	(*CapResponse)(nil), // 1: capitalize_service.CapResponse
}
var file_proto_capservice_proto_depIdxs = []int32{
	0, // 0: capitalize_service.CapService.Capitalize:input_type -> capitalize_service.CapRequest
	1, // 1: capitalize_service.CapService.Capitalize:output_type -> capitalize_service.CapResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_capservice_proto_init() }
func file_proto_capservice_proto_init() {
	if File_proto_capservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_capservice_proto_rawDesc), len(file_proto_capservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_capservice_proto_goTypes,
		DependencyIndexes: file_proto_capservice_proto_depIdxs,
		MessageInfos:      file_proto_capservice_proto_msgTypes,
	}.Build()
	File_proto_capservice_proto = out.File
	file_proto_capservice_proto_goTypes = nil
	file_proto_capservice_proto_depIdxs = nil
}
